language: c++

matrix:

matrix:
  include:
#   - dist: bionic
#     compiler: gcc
#     os: linux
#     sudo: required
#     env:
#       - TRAVIS_DIST_NAME="bionic"
    - dist: xenial
      compiler: gcc
      os: linux
      sudo: required
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-9
          - g++-9
      env:
         - TRAVIS_DIST_NAME="xenial"
         
before_install:
  - sudo apt-get update
  - echo '# Install LIBC6'
  - sudo curl -OL http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6_2.27-3ubuntu1_amd64.deb
  - sudo curl -OL http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6-dev_2.27-3ubuntu1_amd64.deb
  - sudo apt install ./libc6_2.27-3ubuntu1_amd64.deb
  - sudo apt install ./libc6-dev_2.27-3ubuntu1_amd64.deb
  - sudo curl -OL http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6_2.29-0ubuntu2_amd64.deb
  - sudo curl -OL http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6-dev_2.29-0ubuntu2_amd64.deb
  - sudo apt install ./libc6_2.29-0ubuntu2_amd64.deb
  - sudo apt install ./libc6-dev_2.29-0ubuntu2_amd64.deb
  - if [[ ( "$TRAVIS_DIST_NAME" == "xenial" ) ]]; then sudo add-apt-repository ppa:fkrull/deadsnakes -y; fi
  - sudo apt-get update
  - sudo apt-get install -y python3.6
  - sudo apt-get install python3-setuptools
  - sudo apt-get install -y python3-pip
  - sudo python3 -m pip install --upgrade pip
  - sudo apt-get install python3-numpy
  - sudo apt-get install libcgal-qt5-dev
  - mkdir -p build
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-9 /usr/bin/gcc
  - gcc --version
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-9 /usr/bin/g++
  - g++ --version
  - sudo apt install cmake
  - sudo apt-mark hold mysql-server-5.7
  - sudo apt upgrade

script:
  - sudo python3 install.py build
  - sudo python3 run_all.py build
  - cd cpp && sudo python3 test.py
after_success:
  - bash push.sh
env:
  global:
    secure: 
