language: c++

matrix:

matrix:
  include:
    - name: "Last Ubuntu 19.10 (Eoan Ermine) with GCC"
      os: linux
      dist: bionic
      group: travis_latest
      env: DOCKER="ubuntu:eoan" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++" TRAVIS_DIST_NAME="eoan"
#     - dist: xenial
#       compiler: gcc
#       os: linux
#       sudo: required
#       env:
#         - TRAVIS_DIST_NAME="xenial"
    - dist: bionic
      compiler: gcc
      os: linux
      sudo: required
      env:
         - TRAVIS_DIST_NAME="bionic"
         
before_install:
  - sudo git clone git://sourceware.org/git/glibc.git
  - cd glibc
  - sudo git checkout glibc-2.28
  - sudo mkdir build
  - cd build
  - sudo ../configure --prefix "$glibc_install"
  - sudo make -j `nproc` 2> /dev/null
  - sudo make install -j `nproc` 2> /dev/null
  - sudo apt-get update
  - if [[ ( "$TRAVIS_DIST_NAME" == "xenial" ) ]]; then sudo add-apt-repository ppa:fkrull/deadsnakes -y; fi
  - if [[ ( "$TRAVIS_DIST_NAME" == "xenial" ) ]]; then sudo apt-get update; fi
  - sudo apt-get install -y python3.6
  - sudo apt-get install python3-setuptools
  - sudo apt-get install -y python3-pip
  - sudo python3 -m pip install --upgrade pip
  - sudo apt-get install python3-numpy
  - sudo apt-get install libcgal-qt5-dev
  - mkdir -p build
  - sudo apt install cmake
  - sudo apt-mark hold mysql-server-5.7
  - sudo apt upgrade

script:
  - sudo python3 install.py build
#   Decomment following code if you have enough RAM to test the previously compiled binary+python program
#   - sudo python3 run_all.py build
  - cd cpp && sudo python3 test.py
after_success:
  - bash push.sh
env:
  global:
    secure: 
