language: c++

matrix:
  include:
#   - dist: bionic
#     compiler: gcc
#     os: linux
#     sudo: required
#     env:
#       - TRAVIS_DIST_NAME="bionic"
  - dist: xenial
    compiler: gcc
    os: linux
    sudo: required
    env:
      - TRAVIS_DIST_NAME="xenial"

before_install:
  - sudo apt-get update
  - if [[ ( "$TRAVIS_DIST_NAME" == "xenial" ) ]]; then sudo add-apt-repository ppa:fkrull/deadsnakes -y; fi
  - sudo apt-get update
  - sudo apt-get install -y python3.6
  - sudo apt-get install python3-setuptools
  - sudo apt-get install -y python3-pip
  - sudo python3 -m pip install --upgrade pip
  - sudo apt-get install python3-numpy
  - sudo apt-get install libcgal-qt5-dev
  - mkdir -p build
script:
  - python3 install.py build
  - sudo python3 run_all.py
  - cd cpp && sudo python3 test.py
after_success:
  - bash push.sh
env:
  global:
    secure: 
