name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]

    steps:
      - uses: actions/checkout@v1
      - name: install and test on ${{ matrix.os }
        continue-on-error: true
      - run: |
          sudo apt-get update
          sudo add-apt-repository ppa:fkrull/deadsnakes
          sudo apt-get update
          sudo apt-get install -y python3.6
          sudo apt-get install python3-setuptools
          sudo apt-get install -y python3-pip
          sudo python3 -m pip install --upgrade pip
          sudo apt-get install python3-numpy
          sudo apt-get install libcgal-qt5-dev
          mkdir -p build
          python3 install.py build
