name: CI
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        include: 
        - os: ubuntu-18.04
          TARGET: x86_64-unknown-linux-musl
          COMPILER: gcc
          LINKER: gcc

        - os: ubuntu-16.04
          TARGET: x86_64-unknown-linux-musl
          COMPILER: gcc
          LINKER: gcc
    steps:
     - uses: actions/checkout@v1
     - name: installAndTest 16
       if: runner.os == 'ubuntu-16.04'
       run: |
          sudo apt-get update	
          sudo add-apt-repository ppa:fkrull/deadsnakes	
          sudo apt-get update	
          sudo apt-get install -y python3.6	
          sudo apt-get install python3-setuptools	
          sudo apt-get install -y python3-pip	
          sudo python3 -m pip install --upgrade pip	
          sudo apt-get install python3-numpy	
          sudo apt-get install libcgal-qt5-dev	
          mkdir -p build	
          python3 install.py build
     - name: installAndTest 18
       if: runner.os == 'ubuntu-18.04'
       run: |
          sudo apt-get update	
          sudo apt-get install -y python3.6	
          sudo apt-get install python3-setuptools	
          sudo apt-get install -y python3-pip	
          sudo python3 -m pip install --upgrade pip	
          sudo apt-get install python3-numpy	
          sudo apt-get install libcgal-qt5-dev	
          mkdir -p build	
          python3 install.py build
