name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]

    steps:
      - uses: actions/checkout@v1
      - name: install and test on ${{ matrix.os }
        continue-on-error: true
      - run: echo ${{matrix.TARGET}}
