name: CI

on: [push]

jobs:
  build:
    
    strategy:
      fail-fast: false
      
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: using python install.py script
      continue-on-error: true
      run: |
        sudo apt-get update
        sudo add-apt-repository ppa:fkrull/deadsnakes
        sudo apt-get update
        sudo apt-get install -y python3.6
        sudo apt-get install python3-setuptools
        sudo apt-get install -y python3-pip
        sudo python3 -m pip install --upgrade pip
        sudo apt-get install python3-numpy
        sudo apt-get install libcgal-qt5-dev
        mkdir -p build
        python3 install.py build
    - name: configure
      run: |
        ls
        cd /home/runner/work/inverseCSG/inverseCSG/sketch-backend
        sudo ./configure
#     - name: manually building 
#       continue-on-error: true
#       run: |
#         sudo apt-get install gcc-6 g++-6 -y
#         sudo apt-get install gcc-8 g++-8 -y
#         sudo apt-get install build-essential autoconf libtool flex bison mercurial zsh cmake -y
#         sudo python3 -m pip install numpy scipy matplotlib ipython jupyter pandas sympy nose
#         sudo python3 -m pip install -U scikit-learn
#         cd build/
#         ls
#         cd CGAL-4.12/
#         ls
#         cd demo/
#         ls
#         cd Mesh_2/
#         ls
#         cd /home/runner/work/inverseCSG/inverseCSG
#         sudo cmake cpp/
#         sudo make
#         cd /home/runner/work/inverseCSG/inverseCSG/
#         #sudo apt-get install zypper
#         #sudo zypper install -t pattern "devel_C_C++" "devel_java"
#         #sudo zypper install java-1_6_0-openjdk-devel mercurial
#         hg clone https://bitbucket.org/gatoatigrado/sketch-backend
#         hg clone https://bitbucket.org/gatoatigrado/sketch-frontend
#         cd sketch-backend
#         bash autogen.sh
#         ./configure
#         sudo make -j2
#         cd ../sketch-frontend
#         sudo make system-install DESTDIR=/usr/bin SUDOINSTALL=1
#         sudo apt-get install mvn
#         sudo apt-get install mvn
#         sudo apt-get install maven
#         sudo make system-install DESTDIR=/usr/bin SUDOINSTALL=1
#         cd /home/runner/work/inverseCSG/inverseCSG/
#         python3 run_tests.py build/ one_cube
